spring.datasource.username=postgres
spring.datasource.password=D
spring.datasource.url=jdbc:postgresql://localhost:5432/satellitess
spring.jpa.show-sql=true

spring.jpa.hibernate.ddl-auto=create
allowed.origin=http://localhost:5173
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true



