spring.datasource.username=davron
spring.datasource.password=TClM4it0pYg378oF5WdEvWF5kld4awa3
spring.datasource.url=jdbc:postgresql://dpg-d3gg6b2li9vc73f4037g-a.singapore-postgres.render.com/satellite_bi7w
spring.jpa.show-sql=true

spring.jpa.hibernate.ddl-auto=update
allowed.origin=https://satellitess.com    
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true



