spring.datasource.username=satellitedatabase_user
spring.datasource.password=27WeY2ncaSi6DNnuVrdWZAlv8auTacJ7
spring.datasource.url=jdbc:postgresql://dpg-d2s2g43ipnbc73e5mi90-a.singapore-postgres.render.com/satellitedatabase
spring.jpa.show-sql=true

spring.jpa.hibernate.ddl-auto=update
allowed.origin=https://satellitess.com    
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true



